{% set name = "aiida-quantumespresso" %}
{% set version = "4.5.0" %}
{% set build = 0 %}
{% set name_code = name + ".code" %}

package:
  name: {{ name|lower }}.meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4bbc82bc6571814447026913af248db0fefa68e0f39dc3dee4290b2e84879d7c

build:
  number: {{ build }}
  noarch: python

requirements:
  run:
    - {{ pin_subpackage(name, exact=True) }}
    - {{ pin_subpackage(name_code, exact=True) }}

outputs:

  - name: {{ name }}
    build:
      noarch: python
      script: 'python -m pip install . --no-deps --ignore-installed -vvv '
    requirements:
      host:
        - flit-core >=3.4,<4
        - pip
        - python >=3.8
      run:
        - aiida-core.atomic_tools ~=2.3
        - aiida-pseudo ~=1.1
        - click ~=8.0
        - importlib_resources
        - jsonschema
        - numpy
        - packaging
        - pydantic ~=2.0
        - python >=3.8
        - qe-tools ~=2.0
        - xmlschema ~=2.0
      run_constrained:
        - {{ name_code }} =={{ version }}
    test:
      imports:
        - aiida_quantumespresso
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name_code }}
    build:
      noarch: python
    requirements:
      run:
        - qe >=6.6,<=7.2
    test:
      commands:
        - which pw.x

about:
  home: https://pypi.org/project/aiida-quantumespresso/
  summary: The official AiiDA plugin for Quantum ESPRESSO
  dev_url: https://github.com/aiidateam/aiida-quantumespresso
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
    - mbercx
    - sphuber
